# Github workflow for Python script
name: update_worklog

on:
    workflow_dispatch:
    schedule:
        - cron: '30 13 * * *'

jobs:
    update_worklog:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.x'

            - name: Run update_worklog python script
              run: |
                  python update_worklog.py
              env:
                  KRONOS_EMAIL: ${{ secrets.KRONOS_EMAIL }}
                  KRONOS_PASSWORD: ${{ secrets.KRONOS_PASSWORD }}

            - name: PingMe On Pushbullet
              uses: kha7iq/pingme-action@v1
              with:
                service: pushbullet
              env:
                PUSHBULLET_TOKEN: ${{ secrets.PUSHBULLET_TOKEN }}
                PUSHBULLET_DEVICE: ${{ secrets.PUSHBULLET_DEVICE }}
                PUSHBULLET_TITLE: 'Kronos Worklog Updated'
                PUSHBULLET_MESSAGE: |
                  Reference: ${{ github.ref }}
                  Event is triggered by ${{ github.event_name }}
                  Workflow: ${{ github.workflow }}
                  Workflow Log: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
